# 1. Database Connection (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/queryflow_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate Settings (The Magic Table Creator)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. AI Connection (Ollama in Docker)
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3